services:
  - type: web
    name: odonata-classification
    env: python
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app
    